config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'signup'     => 'users#new'
  get 'login'      => 'sessions#new'
  post 'login'     => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users, except: :new
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  serialize :safety
  serialize :highlights
  serialize :favorites
  serialize :standouts

  SPACE      = ['entire_place', 'private_room'].freeze
  KIND       = ['apartment', 'house', 'cabin', 'boat_house'].freeze
  SAFETY     = ['smoke_alarm', 'first_aid_kit', 'fire_extinguisher'].freeze
  HIGHLIGHTS = ['peaceful', 'unique', 'family_friendly', 'stylish', 'central', 'spacious'].freeze
  FAVORITES  = ['wifi', 'tv', 'kitchen', 'washer', 'free_parking', 'air_conditioning', 'dedicated_workspace', 'outdoor_shower'].freeze
  STANDOUTS  = ['pool', 'hot_tub', 'patio', 'BBQ_grill', 'fire_pit', 'pool_table', 'indoor_fireplace', 'outdoor_dining_area', 'exercise_equipment'].freeze

  validates_inclusion_of :space,      in: SPACE
  validates_inclusion_of :kind,       in: KIND
  validates_inclusion_of :safety,     in: SAFETY,     allow_blank: true
  validates_inclusion_of :highlights, in: HIGHLIGHTS, allow_blank: true
  validates_inclusion_of :favorites,  in: FAVORITES,  allow_blank: true
  validates_inclusion_of :standouts,  in: STANDOUTS,  allow_blank: true

  validates_length_of     :description, within: 50..400
  validates_length_of     :address,     within: 1..255
  validates_presence_of   :city,        within: 1..20
  validates_presence_of   :zip,         within: 1..7
  validates_format_of     :zip,         with: /\A[A-Za-z0-9\- ]+\Z/
  validates_presence_of   :country,     within: 0..30
  validates               :guests,      numericality: { only_integer: true }
  validates               :beds,        numericality: { only_integer: true }
  validates               :bedrooms,    numericality: { only_integer: true }
  validates               :bathrooms,   numericality: { only_integer: true }
  validates_uniqueness_of :headline,    allow_blank: false     
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :avatar

  validates :email, presence: true, uniqueness: true, on: :create
  validates :password, length: { minimum: 8 }, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action."
      redirect_to login_path
    end
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      flash[:notice] = 'Your flat has benn saved!'
      redirect_to @flat
    else
      render :new
    end
  end

  private

  def flat_params
    params.require(:flat)
      .permit(:kind,
        :space,
        :address,
        :address_description,
        :city,
        :zip,
        :country,
        :guests,
        :beds,
        :bedrooms,
        :bathrooms,
        :standouts,
        :favorites,
        :safety,
        :headline,
        :highlights,
        :description
      )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully."
      redirect_to root_path
    else
      flash.now[:alert] = "There was something wrong with your login details."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(create_user_params)
    byebug

    if @user.save
      flash[:notice] = 'User created'
      redirect_to login_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(edit_user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def create_user_params
    params.require(:user).permit(:email, :password)
  end

  def edit_user_params
    params.require(:user).permit(:first_name, :last_name, :avatar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
  def select_options(options)
    select_options = options.map do |option|
      [option.humanize, option]
    end
  end
end

app/views/flats/_form.haml
= form_with model: @flat, local: true do |f|
  %div
    = f.label :kind
    = f.select :kind, select_options(Flat::KIND), { include_blank: true }
    - @flat.errors.full_messages_for(:kind).each do |message|
      %p= message

  %div
    = f.label :space
    = f.select :space, select_options(Flat::SPACE), { include_blank: true }
    - @flat.errors.full_messages_for(:space).each do |message|
      %p= message

  %div
    = f.label :address
    = f.text_field :address
    - @flat.errors.full_messages_for(:address).each do |message|
      %p= message

  %div
    = f.label :address_description
    = f.text_field :address_description
    - @flat.errors.full_messages_for(:address_description).each do |message|
      %p= message

  %div
    = f.label :city
    = f.text_field :city
    - @flat.errors.full_messages_for(:city).each do |message|
      %p= message

  %div
    = f.label :zip
    = f.number_field :zip
    - @flat.errors.full_messages_for(:zip).each do |message|
      %p= message

  %div
    = f.label :country
    = f.text_field :country
    - @flat.errors.full_messages_for(:country).each do |message|
      %p= message

  %div
    = f.label :guests
    = f.number_field :guests
    - @flat.errors.full_messages_for(:guests).each do |message|
      %p= message

  %div
    = f.label :beds
    = f.number_field :beds
    - @flat.errors.full_messages_for(:beds).each do |message|
      %p= message
    
  %div
    = f.label :bedrooms
    = f.number_field :bedrooms
    - @flat.errors.full_messages_for(:bedrooms).each do |message|
      %p= message
    
  %div
    = f.label :bathrooms
    = f.number_field :bathrooms
    - @flat.errors.full_messages_for(:bathrooms).each do |message|
      %p= message
    
  %div
    = f.label :standouts
    = f.label :pool
    = check_box_tag 'standouts[]', 'pool', false, id: 'pool'

    = f.label :hot_tub
    = check_box_tag 'standouts[]', 'hot_tub', false, id: 'hot_tub'

    = f.label :patio
    = check_box_tag 'standouts[]', 'patio', false, id: 'patio'

    = f.label :BBQ_grill
    = check_box_tag 'standouts[]', 'BBQ_grill', false, id: 'BBQ_grill'

    = f.label :fire_pit
    = check_box_tag 'standouts[]', 'fire_pit', false, id: 'fire_pit'

    - @flat.errors.full_messages_for(:standouts).each do |message|
      %p= message
    
  %div
    = f.label :favorites
    = f.select :favorites, select_options(Flat::FAVORITES), { include_blank: :select }
    - @flat.errors.full_messages_for(:favorites).each do |message|
      %p= message
    
  %div
    = f.label :safety
    = f.select :safety, select_options(Flat::SAFETY), { include_blank: true }
    - @flat.errors.full_messages_for(:safety).each do |message|
      %p= message
    
  %div
    = f.label :headline
    = f.text_field :headline
    - @flat.errors.full_messages_for(:headline).each do |message|
      %p= message
    
  %div
    = f.label :highlights
    = f.select :highlights, select_options(Flat::HIGHLIGHTS), { include_blank: true }
    - @flat.errors.full_messages_for(:highlights).each do |message|
      %p= message
    
  %div
    = f.label :description
    = f.text_area :description
    - @flat.errors.full_messages_for(:description).each do |message|
      %p= message

  %div
    = f.submit
    

app/views/flats/index.haml
%h1 Flats

- @flats.each do |flat|
  = link_to flat.headline, flat_path(flat)
  %div
    %p= flat.description

= link_to 'New Flat', new_flat_path

app/views/flats/new.haml
%h1 New Flat
= render 'form'

app/views/flats/show.haml
%h1= @flat.headline

%table
  %tr
    - @flat.attributes.keys.each do |key|
      %th= key
  %tr
    - @flat.attributes.values.each do |value|
      %td= value

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flatswap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_edit_form.haml
= form_with model: @user do |f|
  %div
    = f.label :first_name
    = f.text_field :first_name
    - @user.errors.full_messages_for(:first_name).each do |message|
      %p= message

  %div
    = f.label :last_name
    = f.text_field :last_name
    - @user.errors.full_messages_for(:last_name).each do |message|
      %p= message

  %div
    = f.label :avatar
    = f.file_field :avatar

  %div
    = f.submit

app/views/users/_form.haml
= form_with model: @user, local: true do |f|
  %div 
    = f.label :email
    = f.email_field :email
    - @user.errors.full_messages_for(:email).each do |message|
      %p= message

  %div
    = f.label :password
    = f.password_field :password
    - @user.errors.full_messages_for(:password).each do |message|
      %p= message

  %div
    = f.submit

app/views/users/edit.haml
%h1 Edit User
= render 'edit_form'

app/views/users/new.haml
%h1 New User
= render 'form'

app/views/users/show.haml
%h1= "Welcome #{ @user.first_name && @user.first_name }"

- if @user.avatar&.attached?
  = image_tag @user.avatar

= link_to 'Settings', edit_user_path(@user.id)

app/views/welcome/index.haml
%h1 Flat Swap

%div
  - if logged_in?
    = link_to 'Profile', user_path(current_user.id)
    = link_to 'Log out', logout_path, method: :delete
  - else
    = link_to 'Signup', signup_path
    = link_to 'Log in', login_path
    = link_to 'Flats', flats_path